# Generated by Django 5.1.1 on 2024-09-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_inbound_status_alter_inventory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='product_received',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.inventory'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.customer'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='product_shipped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.inventory'),
        ),
    ]
