# Generated by Django 5.1.1 on 2024-09-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_inbound_product_received_inbound_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='tags',
            field=models.ManyToManyField(to='warehouse.tag'),
        ),
    ]
